### ISSUE TITLE
Rolling back multiple updates to the same field together only rolls back the most recent change

### ISSUE THREAD

**Issue by BenGrav** [thomasdayman/XrmToolBox_AuditHistoryRollBack#2]
For example if the Name field was changed from **A** to **B**, and then from **B** to **C**, and you rollback both updates together, then it will revert the field back to **B**
The expected behaviour would be to return the field back to its original state before all updates to it within the selected audit history records

Rolling back all these selected records:
![image](https://user-images.githubusercontent.com/88517127/135546850-292e0fa5-878b-43ff-a77b-5907c79f440a.png)

Results in this:
![image](https://user-images.githubusercontent.com/88517127/135546918-77e49f21-a3df-4dc3-af48-9f0d99312f30.png)

**Comment by thomasdayman** [comment]
Thanks @BenGrav for pointing this out. At the moment I am just updating the record once in one transaction. This meant that if you were to do multiple rollbacks on the same field then it will only update that field it once, which is what you found in this raised issue.

To fix this I would need to update the record per audit history line which is highlighted. For example if there are 8 lines highlighted then I will need to update the record 8 times rather than once. Which seems overkill but seems to be the only solution to fix this sort of problem. I will let you know when this problem is fixed.

**Comment by thomasdayman** [comment]
@BenGrav I have fixed the bug and uploaded it to XRMToolBox. You will need to wait a little while before it gets published. When you get the new update could you confirm that its has solved the problem?

**Comment by BenGrav** [comment]
Yes, this is working as expected, many thanks!
